#!/bin/bash

rm -rf build/*
mkdir -p build

# All files
node_modules/.bin/tsc --noImplicitAny --noEmitOnError --declaration --m commonjs -out build/chronoshift.js \
  src/init.ts \
  \
  src/timezone.ts \
  src/floor_move_ceil.ts \
  src/duration.ts \
  \
  src/exports.ts \
  && \
  node extra/extra.js;
