#!/bin/bash -e

if grep -rq 'describe\.only' ./test
  then
    echo "describe.only found. Please update your test"
    exit 1
fi

if grep -rq 'it\.only' ./test
  then
    echo "it.only found. Please update your test"
    exit 1
fi

./compile
mocha --compilers js:babel-core/register build/**/*.mocha.js
mocha test/*.js
